### ISSUE TITLE
Wires

### ISSUE THREAD

**Issue by hirobius** [hirobius/memory-game#3]
![memory_play@2x](https://user-images.githubusercontent.com/75229244/109753022-51a4d580-7b96-11eb-9fb0-cdda6d154130.png)
![memory_playing@2x](https://user-images.githubusercontent.com/75229244/109753042-5bc6d400-7b96-11eb-8d6d-fd14c780dfdf.png)
![memory_results@2x](https://user-images.githubusercontent.com/75229244/109753057-63867880-7b96-11eb-91ed-1fc04dd595d1.png)
![memory_scoreboard@2x](https://user-images.githubusercontent.com/75229244/109753069-697c5980-7b96-11eb-9815-a500c619b5f1.png)

**Comment by adr-eng** [comment]
![memory_difficultySelect@2x](https://user-images.githubusercontent.com/75229244/109753184-a47e8d00-7b96-11eb-8886-b121d9be3a21.png)
